services:
  rmq:
    image: rabbitmq:3-management
    container_name: rmq
    hostname: rmq
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: changeme
    restart: unless-stopped

  couchdb:
    image: couchdb:latest
    container_name: couchdb
    hostname: couchdb
    ports:
      - "5984:5984" # CouchDB HTTP API
    volumes:
      - $PWD/couchdb.ini:/opt/couchdb/etc/local.ini
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: changeme
    restart: unless-stopped